Jaguarete_Kaa/Carrito/urls.py
from django.urls import path
from . import views

app_name = "carro"

urlpatterns = [
    path("agregar/<int:producto_id>/", views.agregar_producto, name="Agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="Eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="Restar"),
    path("limpiar/", views.limpiar_carro, name="Limpiar"),
]

Jaguarete_Kaa/Contacto/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.contacto, name="Contacto"),
]

Jaguarete_Kaa/Jaguarete_App/urls.py
from django.urls import path
from Jaguarete_App import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name="Home"),
    path('about/', views.about, name="About"),
    path('categoria/', views.categoria, name="Categoria"),
    path('carrito/', views.carro, name="Carrito"),
    path('login/', views.login, name="LogIn"),
    path('register/', views.register, name="Register"),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Jaguarete_Kaa/Jaguarete_Kaa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Jaguarete_App.urls")),
    path('contacto/', include("Contacto.urls")),
    path('carrito/', include("Carrito.urls")),
]

Jaguarete_Kaa/Carrito/models.py
from django.db import models

# Create your models here.
class CategoriaProducto(models.Model):
    nombre = models.CharField(max_length=45)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = "categoria_producto"
        verbose_name_plural = "categorias_productos"
    
    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    categorias = models.ForeignKey(CategoriaProducto, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="carrito", null=True, blank=True)
    precio = models.FloatField()
    disponibilidad = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = "producto"
        verbose_name_plural = "productos"

Jaguarete_Kaa/Contacto/models.py
from django.db import models

# Create your models here.

Jaguarete_Kaa/Jaguarete_App/models.py
from django.db import models

# Create your models here.

Jaguarete_Kaa/Contacto/forms.py
from django import forms
from django.forms.widgets import Textarea 

class FormularioContacto(forms.Form):
    nombre = forms.CharField(label="Nombre", required=True)
    apellido = forms.CharField(label="Apellido", required=True)
    email = forms.EmailField(label="Email", required=True)
    contenido = forms.CharField(label="Contenido", widget=forms.Textarea)

Jaguarete_Kaa/Carrito/views.py
from django.shortcuts import render, redirect
from .carro import Carro
from .models import Producto

# Create your views here.
def agregar_producto(request, producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id=producto_id)
    carro.agregar(producto=producto)
    return redirect("Carro")

def eliminar_producto(request, producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id=producto_id)
    carro.eliminar(producto=producto)
    return redirect("Carro")

def restar_producto(request, producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id=producto_id)
    carro.restar_producto(producto=producto)
    return redirect("Carro")

def limpiar_carro(request, producto_id):
    carro = Carro(request)
    carro.limpiar_carro()
    return redirect("Carro")

Jaguarete_Kaa/Contacto/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import redirect, render
from .forms import FormularioContacto

# Create your views here.
def contacto(request):
    formulario = FormularioContacto()
    
    if request.method == "POST":
        formulario = FormularioContacto(data=request.POST)
        if formulario.is_valid():
            nombre = request.POST.get("nombre")
            apellido = request.POST.get("apellido")
            email = request.POST.get("email")
            contenido = request.POST.get("contenido")
    
    return render(request, 'Contacto/contacto.html', {
        "miFormulario": formulario
    })

Jaguarete_Kaa/Jaguarete_App/views.py
from django.shortcuts import render
from Carrito.models import Producto

# Create your views here.
def home(request):
    return render(request, 'Jaguarete_App/home.html')

def about(request):
    return render(request, 'Jaguarete_App/about.html')

def categoria(request):
    return render(request, 'Jaguarete_App/categoria.html')

def carro(request):
    productos = Producto.objects.all()
    return render(request, 'Jaguarete_App/carrito.html', {
        "productos": productos
    })

# Cambiar views despues de hacer su respectivo login / register
def login(request):
    return render(request, 'Jaguarete_App/login.html')

def register(request):
    return render(request, 'Jaguarete_App/register.html')

Jaguarete_Kaa/Contacto/templates/Contacto/contacto.html
{% extends 'Jaguarete_App/layout.html' %}

{% block title %}Contacto{% endblock %}

{% load static %}

{% block content %}

    <div class="contenedorFormulario">
        <form action="" class="row g-3" method="POST">
            {% csrf_token %}
            <div class="col-md-6">
                <label for="inputText" class="form-label">Nombre</label>
                <input type="text" class="form-control" id="inputText4" name="nombre">
            </div>
            <div class="col-md-6">
                <label for="inputText" class="form-label">Apellido</label>
                <input type="text" class="form-control" id="inputText4" name="apellido">
            </div>
            <div class="col-12">
                <label for="inputEmail" class="form-label">Email</label>
                <input type="email" class="form-control" id="inputEmail4" placeholder="example@mail.com" name="email">
            </div>
            <div class="col-12">
                <label for="inputText" class="form-label">Mensaje</label>
                <textarea type="textArea" class="form-control" id="inputText" placeholder="Introduzca su mensaje aquí" name="contenido"></textarea>
            </div>
            <div class="col-12">
                <button type="submit" class="btn btn-primary">Enviar</button>
            </div>
        </form>
    </div>

{% endblock %}

Jaguarete_Kaa/Jaguarete_App/templates/Jaguarete_App/about.html
{% extends 'Jaguarete_App/layout.html' %}

{% block title %}About Us{% endblock %}

{% load static %}

{% block content %}

    <h3 style="text-align: center;">Acerca de nuestro comercio</h3>
    <img src="{% static '/imagenes/imagen-ejemplo.jpg' %}" alt="" width="500" height="300" style="margin: 10px auto 10px; display: block;">
    <div class="d-flex justify-content-center"">
        <p style="text-align: center; margin: 10px 10px 30px 30px;">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusamus nesciunt vero deserunt alias debitis dicta dolore, nostrum in aliquid! Velit, sint! Atque voluptas corporis odit necessitatibus. Laborum soluta voluptate voluptatum! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed officia quisquam laudantium amet! Consequuntur voluptatum suscipit debitis autem voluptas mollitia. Aspernatur cupiditate iusto maxime nam obcaecati facilis. Doloremque, id mollitia? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsum commodi amet hic laboriosam error natus repellat quidem in. Similique voluptatibus rem molestias repellat laudantium magni. Aliquam deserunt repudiandae perferendis necessitatibus.</p>
    </div>
    
{% endblock %}

Jaguarete_Kaa/Jaguarete_App/templates/Jaguarete_App/carrito.html
{% extends 'Jaguarete_App/layout.html' %}

{% block title %}Carrito{% endblock %}

{% load static %}

{% block content %}

    <div class="container">

        <div style="float: right;">
            {% include "Jaguarete_App/widget.html" %}
        </div>

        <div class="row">

            {% for producto in productos %}
                
                <div class="col-md-3">
                    <div class="card" style="width: 100%; margin: 5px 5px;">
                        <img src="{{ producto.imagen.url }}" alt="" class="card-img-top">
                        <div class="card-body" style="text-align: center;">
                            <h6 class="card-title">{{ producto.nombre }}</h6>
                            <p class="card-text">{{ producto.precio }}&nbsp;$</p>
                        </div>
                        <div class="card-footer text-center">
                            <a href="{% url 'carro:Agregar' producto.id %}" class="btn btn-success">Agregar al carro</a>
                        </div>
                    </div>
                </div>

            {% endfor %}

        </div>
    </div>
    
{% endblock %}

Jaguarete_Kaa/Jaguarete_App/templates/Jaguarete_App/categoria.html
{% extends 'Jaguarete_App/layout.html' %}

{% block title %}Categoria{% endblock %}

{% load static %}

{% block content %}

    <!-- Usar card de boostrap -->
    <div class="card-group">
        <div class="card">
            <img src="{% static 'imagenes/instrumentos.jpg' %}" class="card-img-top" alt="">
            <div class="card-body">
                <h5 class="card-title">Instrumentos</h5>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
        </div>
        <div class="card">
            <img src="{% static 'imagenes/deportes.jpg' %}" class="card-img-top" alt="">
            <div class="card-body">
                <h5 class="card-title">Deportes</h5>
                <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
        </div>
        <div class="card">
            <img src="{% static 'imagenes/tecnologia.jpeg' %}" class="card-img-top" alt="">
            <div class="card-body">
                <h5 class="card-title">Tecnologia</h5>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
        </div>
    </div>

{% endblock %}

Jaguarete_Kaa/Jaguarete_App/templates/Jaguarete_App/home.html
{% extends 'Jaguarete_App/layout.html' %}

{% block title %}Home{% endblock %}

{% load static %}

{% block content %}

    <h1>Bienvenidos a Jaguarete Kaa</h1>
    <section class="article-list">
        <div class="container">
            <div class="intro">
                <h2 class="title">¿Que ofrecemos?</h2>
                <p class="text-center">Nunc luctus in metus eget fringilla. Aliquam sed justo ligula. Vestibulum nibh erat, pellentesque ut laoreet vitae. </p>
            </div>
            <div class="row articles">
                <div class="col-sm-6 col-md-4 item">
                    <a href="#"><img class="img-fluid" src="{% static 'imagenes/notebook.jpg' %}" /></a>
                    <h3 class="name">Solucion</h3>
                    <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, interdum justo suscipit id.</p>
                    <a class="action" href="#"><i class="fa fa-arrow-circle-right"></i></a>
                </div>
                <div class="col-sm-6 col-md-4 item">
                    <a href="#"><img class="img-fluid" src="{% static 'imagenes/oficina.webp' %}" /></a>
                    <h3 class="name">Atencion</h3>
                    <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, interdum justo suscipit id.</p>
                    <a class="action" href="#"><i class="fa fa-arrow-circle-right"></i></a>
                </div>
                <div class="col-sm-6 col-md-4 item">
                    <a href="#"><img class="img-fluid" src="{% static 'imagenes/envios.png' %}" /></a>
                    <h3 class="name">Envios</h3>
                    <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, interdum justo suscipit id.</p>
                    <a class="action" href="#"><i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

Jaguarete_Kaa/Jaguarete_App/templates/Jaguarete_App/layout.html
<!DOCTYPE html>
<html lang="es">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static '/css/estilo.css' %}">

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    </head>
    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <!-- Logo -->
                <a class="navbar-brand" href="{% url 'Home' %}">
                    <img src="{% static '/imagenes/logo-jaguarete.png' %}" alt="" width="50" height="50" class="d-inline-block align-text-center">
                    Jaguarete Kaa
                </a>
                <!-- Botones -->
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="{% url 'LogIn' %}" type="button" class="btn btn-outline-secondary btn-sm"><span class="material-icons">login</span><span> Login</span></a>
                    <a href="{% url 'Register' %}" type="button" class="btn btn-outline-secondary btn-sm"><span class="material-icons">person_add_alt</span> Registrar</a>
                    <a href="{% url 'Carrito' %}" type="button" class="btn btn-outline-secondary btn-sm"><span class="material-icons">shopping_cart</span> Carrito</a>
                </div>
            </div>
        </nav>

        <!-- Menu de navegacion -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <ul class="nav nav-pills nav-fill">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/' %} active {% endif %}" href="{% url 'Home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/categoria/' %} active {% endif %}" href="{% url 'Categoria' %}">Categorias</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/about/' %} active {% endif %}" href="{% url 'About' %}">Acerca de</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/contacto/' %} active {% endif %}" href="{% url 'Contacto' %}">Contacto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Nuevo producto</a>
                    </li>
                </ul>

                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit" style="background-color: rgb(15, 119, 179) !important; border-color: azure !important; color: snow !important;">Search</button>
                </form>

                <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span> 
                </button> -->
            </div>
        </nav>

        {% block content %}{% endblock %}

        <!-- Footer -->
        <footer class="footer-basic" style="text-align: center;">
            <div class="social">
                <a href="#">
                    <i class="icon ion-social-instagram"></i>
                </a>
                <a href="#">
                    <i class="icon ion-social-twitter"></i>
                </a>
                <a href="#">
                    <i class="icon ion-social-facebook"></i>
                </a>
            </div>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Home</a></li>
                <li class="list-inline-item"><a href="#">Services</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <p class="copyright">Jaguarete Kaa © 2021</p>
        </footer>

        <!-- Bootstrap.js -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        
    </body>
</html>

Jaguarete_Kaa/Jaguarete_App/templates/Jaguarete_App/login.html
{% extends 'Jaguarete_App/layout.html' %}

{% block title %}LogIn{% endblock %}

{% load static %}

{% block content %}

    <h1>Log In</h1>
    <div class="contenedorFormulario">
        <form>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Correo</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Contraseña</label>
                <input type="password" class="form-control" id="exampleInputPassword1">
            </div>
            <div class="mb-3 form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Remember me</label>
            </div>
            <button type="submit" class="btn btn-primary">Ingresar</button>
        </form>
    </div>

{% endblock %}

Jaguarete_Kaa/Jaguarete_App/templates/Jaguarete_App/register.html
{% extends 'Jaguarete_App/layout.html' %}

{% block title %}Register{% endblock %}

{% load static %}

{% block content %}

    <h1>Registrese</h1>
    <div class="contenedorFormulario">
        <form class="row g-3">
            <div class="col-md-4">
                <label for="validationDefault01" class="form-label">Nombres</label>
                <input type="text" class="form-control" id="validationDefault01" value="" required>
            </div>
            <div class="col-md-4">
                <label for="validationDefault02" class="form-label">Apellidos</label>
                <input type="text" class="form-control" id="validationDefault02" value="" required>
            </div>
            <div class="col-md-4">
                <label for="validationDefaultUsername" class="form-label">Username</label>
                <div class="input-group">
                    <span class="input-group-text" id="inputGroupPrepend2">@</span>
                    <input type="text" class="form-control" id="validationDefaultUsername"  aria-describedby="inputGroupPrepend2" required>
                </div>
            </div>
            <div class="col-md-6">
                <label for="validationDefault03" class="form-label">Ciudad</label>
                <input type="text" class="form-control" id="validationDefault03" required>
            </div>
            <div class="col-md-3">
                <label for="validationDefault04" class="form-label">State</label>
                <select class="form-select" id="validationDefault04" required>
                    <option selected disabled value="">-</option>
                    <option>Argentina</option>
                    <option>Otro</option>
                </select>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Contraseña</label>
                <input type="password" class="form-control" id="exampleInputPassword1">
            </div>
            <div class="col-12">
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="invalidCheck2" required>
                    <label class="form-check-label" for="invalidCheck2">
                    Agree to terms and conditions
                    </label>
                </div>
            </div>
            <div class="col-12">
                <button class="btn btn-primary" type="submit">Registrarme</button>
            </div>
        </form>
    </div>


{% endblock %}

Jaguarete_Kaa/Jaguarete_App/templates/Jaguarete_App/widget.html
<table class="table table-bordered" style="color: white;">

    <thead>
        <tr>
            <th colspan="3" class="text-center">
                Carro compras
            </th>
        </tr>

        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>
        </tr>
    </thead>

    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">
                    <td>{{ value.nombre }}</td>
                    <td>{{ value.cantidad }}</td>
                    <td>
                        <a href="{% url 'carro:Agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:Restar' value.producto_id %}" class="btn btn-sm btn-success">-</a>

                        {{ value.precio }}
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin productos
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">
                Total: {{ importe_total_carro }}
            </td>
        </tr>
    </tfoot>

</table>